jobs:
  build:
    docker:
      - image: buildpack-deps:trusty # primary container
        auth:
          username: neleleonemack
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          ENV: CI